- src/main/kotlin/com/jetbrains/snakecharm/codeInsight/completion/SMKShadowSettingsCompletionContributor.kt
- src/main/kotlin/com/jetbrains/snakecharm/lang/psi/SMKRuleParameterListStatement.kt
- src/main/resources/META-INF/plugin.xml
- src/test/resources/com/jetbrains/snakecharm/cucumber/completion/shadow_settings.feature
> 'shadow' settings completion added with tests

- src/main/kotlin/com/jetbrains/snakecharm/lang/parser/SnakemakeExpressionParsing.kt
- src/test/kotlin/com/jetbrains/snakecharm/lang/parser/SnakemakeParsingTest.kt
- testData/psi/HangingComa.smk
- testData/psi/HangingComa.txt
> #58 Inspection: trailing coma at the end of snakefile

- src/main/kotlin/com/jetbrains/snakecharm/lang/documentation/SmkShadowSettingsDocumentation.kt
- src/main/resources/META-INF/plugin.xml
- src/test/resources/com/jetbrains/snakecharm/cucumber/documentation/shadow_settings_documentation.feature
> #73 Shadow settings documentation

- src/main/kotlin/com/jetbrains/snakecharm/codeInsight/completion/SMKKeywordCompletionContributor.kt
- src/test/kotlin/com/jetbrains/snakecharm/cucumber/CompletionResolveSteps.kt
- src/test/resources/com/jetbrains/snakecharm/cucumber/completion/keywords.feature
> #69 Input autocompletion bug

- src/main/kotlin/com/jetbrains/snakecharm/codeInsight/completion/SMKKeywordCompletionContributor.kt
- src/test/kotlin/com/jetbrains/snakecharm/cucumber/CompletionResolveSteps.kt
- src/test/resources/com/jetbrains/snakecharm/cucumber/completion/keywords.feature
> #11 Code completon for subworkflow section names

- src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSectionRedeclarationInspection.kt
- src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkShadowMultipleSettingsInspection.kt
- src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSubworkflowMultipleArgsInspection.kt
- src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSubworkflowRedeclarationInspection.kt
- src/main/kotlin/com/jetbrains/snakecharm/lang/psi/SMKElementVisitor.kt
- src/main/kotlin/com/jetbrains/snakecharm/lang/psi/SnakemakeFile.kt
- src/main/kotlin/com/jetbrains/snakecharm/lang/psi/types/SnakemakeRulesType.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/SnakemakeBundle.properties
- src/test/kotlin/com/jetbrains/snakecharm/cucumber/ActionsSteps.kt
- src/test/kotlin/com/jetbrains/snakecharm/cucumber/StepDefs.kt
- src/test/resources/com/jetbrains/snakecharm/cucumber/highlighting/section_redeclaration.feature
- src/test/resources/com/jetbrains/snakecharm/cucumber/highlighting/subworkflow_multiple_args.feature
- src/test/resources/com/jetbrains/snakecharm/cucumber/highlighting/subworkflow_redeclaration.feature
> #88 Subworkflow inspections

- src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSubworkflowRedeclarationInspection.kt
- src/test/resources/com/jetbrains/snakecharm/cucumber/completion/subworkflow_name.feature
- src/test/resources/com/jetbrains/snakecharm/cucumber/resolve/subworkflow_name.feature
> #93 Subworkflow rename bug

- src/main/kotlin/com/jetbrains/snakecharm/codeInsight/SmkSectionTypeProvider.kt
- src/main/kotlin/com/jetbrains/snakecharm/lang/psi/SnakemakeFile.kt
- src/main/kotlin/com/jetbrains/snakecharm/lang/psi/types/SmkCheckPointsType.kt
- src/main/kotlin/com/jetbrains/snakecharm/lang/psi/types/SnakemakeRulesType.kt
- src/main/resources/META-INF/plugin.xml
- src/test/resources/com/jetbrains/snakecharm/cucumber/completion/names_after_section.feature
- src/test/resources/com/jetbrains/snakecharm/cucumber/resolve/names_after_section.feature
> #82 Resolve and completion for 'checkpoints' names

- src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkRuleOrCheckpointNameYetUndefinedInspection.kt
- src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkYetUndefinedNameInspection.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/SnakemakeBundle.properties
- src/main/resources/inspectionDescriptions/SmkRuleOrCheckpointNameYetUndefinedInspection.html
- src/main/resources/inspectionDescriptions/SmkYetUndefinedNameInspection.html
- src/test/kotlin/com/jetbrains/snakecharm/cucumber/StepDefs.kt
- src/test/resources/com/jetbrains/snakecharm/cucumber/highlighting/rule_or_checkpoint_name_yet_undefined.feature
- src/test/resources/com/jetbrains/snakecharm/cucumber/highlighting/yet_undefined_name.feature
> #101 Undefined name warning

- src/main/kotlin/com/jetbrains/snakecharm/lang/psi/impl/SmkPsiUtil.kt
- src/test/resources/com/jetbrains/snakecharm/cucumber/completion/file_completion_in_workflow_sections.feature
> Top-level workflow sections bug

- src/main/kotlin/com/jetbrains/snakecharm/string_language/SmkSLBraceMatcher.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/com/jetbrains/snakecharm/cucumber/ActionsSteps.kt
- src/test/resources/com/jetbrains/snakecharm/cucumber/string_language/brace_matcher.feature
> #181 Implemented brace matcher for SmkString injection language

- src/main/kotlin/com/jetbrains/snakecharm/string_language/SmkSLInjector.kt
- src/test/resources/com/jetbrains/snakecharm/cucumber/string_language/string_language_injection.feature
> #189 Inject Snakemake format language in strings concatenated by `+`

- src/main/kotlin/com/jetbrains/snakecharm/string_language/lang/highlighter/SmkSLRegExpHighlightingAnnotator.kt
> #188 SnakemakeSL NSEE bug

- src/main/kotlin/com/jetbrains/snakecharm/string_language/SmkSLInjector.kt
- src/test/resources/com/jetbrains/snakecharm/cucumber/string_language/string_language_injection.feature
> #201 do not inject smk sl in f strings without { or } in string part

- src/test/resources/com/jetbrains/snakecharm/cucumber/actions/annotator_and_inspection_quick_fixes.feature
Added a test for `SmkLambdaRuleParamsInspection` rename lambda parameter to wildcards action. Somewhat related to #147
> `SmkLambdaRuleParameterInspection` quick fix test

- src/main/kotlin/com/jetbrains/snakecharm/codeInsight/completion/SMKImplicitPySymbolsCompletionContributor.kt
- src/main/kotlin/com/jetbrains/snakecharm/stringLanguage/SmkSLInjector.kt
- src/test/resources/com/jetbrains/snakecharm/cucumber/stringLanguage/string_language_injection.feature
> #228 Inject SmkSL in join

- src/main/kotlin/com/jetbrains/snakecharm/stringLanguage/lang/highlighter/SmkSLHighlightingAnnotator.kt
- src/main/kotlin/com/jetbrains/snakecharm/stringLanguage/lang/psi/elementTypes/SmkSLReferenceExpression.kt
> #227 Wildcards highlighting

- src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSectionDuplicatedArgsInspection.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/SnakemakeBundle.properties
- src/main/resources/inspectionDescriptions/SmkSectionDuplicatedArgsInspection.html
- src/test/resources/features/highlighting/inspections/duplicated_args_inspection.feature
> #263 Warn of duplicates in arguments

- CHANGES
- src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSectionUnspecifiedFieldArgsInspection.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/SnakemakeBundle.properties
- src/main/resources/inspectionDescriptions/SmkSectionMistypedArgsInspection.html
- src/main/resources/inspectionDescriptions/SmkSectionUnspecifiedFieldArgsInspection.html
- src/test/resources/features/highlighting/inspections/section_unspecified_field_args_inspection.feature
> #257 warn of unspecified field arguments

- src/main/kotlin/com/jetbrains/snakecharm/codeInsight/SmkCodeBlockProvider.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/features/glue/ActionsSteps.kt
- src/test/kotlin/features/glue/CompletionResolveSteps.kt
- src/test/resources/features/actions/smk_code_block_provider.feature
Implement CodeBlockProvider EP for snakemake
Fixes: #296
> #296 Implement CodeBlockProvider EP for snakemake

- src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSeveralRulesAreOverriddenAsOneInspection.kt
- src/main/kotlin/com/jetbrains/snakecharm/lang/psi/SmkPsiElements.kt
- src/main/kotlin/com/jetbrains/snakecharm/lang/psi/impl/SmkUseImpl.kt
- src/test/resources/features/highlighting/inspections/several_rules_are_overridden_as_one.feature
> Features/#411 FP was fixed

- CHANGELOG.md
- src/main/kotlin/com/jetbrains/snakecharm/lang/psi/SmkFileReference.kt
- src/main/kotlin/com/jetbrains/snakecharm/lang/psi/impl/SmkRuleOrCheckpointArgsSectionImpl.kt
- src/test/resources/features/completion/path_in_section_completion.feature
- src/test/resources/features/resolve/path_in_section_resolve.feature
Completion and resolve was implemented for 'script' section.   
AFAIU 'notebook' already have such features.
> Features/#426 resolve, completion for script and notebook sections
